#ResNest269
python3 test_template_TTA.py --img_size 320 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_main_track.csv --model_path $2 --model_type RESNEST269 --load $2/33.pth --valid_mat $2/33_test_tta_main.mat --kaggle_csv_log $2/33_test_tta_main.log
python3 test_template_TTA.py --img_size 320 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_freq_track.csv --model_path $2 --model_type RESNEST269 --load $2/33.pth --valid_mat $2/33_test_tta_freq.mat --kaggle_csv_log $2/33_test_tta_freq.log
python3 test_template_TTA.py --img_size 320 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_comm_track.csv --model_path $2 --model_type RESNEST269 --load $2/33.pth --valid_mat $2/33_test_tta_comm.mat --kaggle_csv_log $2/33_test_tta_comm.log
python3 test_template_TTA.py --img_size 320 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_rare_track.csv --model_path $2 --model_type RESNEST269 --load $2/33.pth --valid_mat $2/33_test_tta_rare.mat --kaggle_csv_log $2/33_test_tta_rare.log

#Swin
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_main_track.csv --model_path $2 --model_type SWIN --load $2/40.pth --valid_mat $2/40_test_tta_main.mat --kaggle_csv_log $2/40_test_tta_main.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_freq_track.csv --model_path $2 --model_type SWIN --load $2/40.pth --valid_mat $2/40_test_tta_freq.mat --kaggle_csv_log $2/40_test_tta_freq.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_comm_track.csv --model_path $2 --model_type SWIN --load $2/40.pth --valid_mat $2/40_test_tta_comm.mat --kaggle_csv_log $2/40_test_tta_comm.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_rare_track.csv --model_path $2 --model_type SWIN --load $2/40.pth --valid_mat $2/40_test_tta_rare.mat --kaggle_csv_log $2/40_test_tta_rare.log

python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_main_track.csv --model_path $2 --model_type SWIN --load $2/22.pth --valid_mat $2/22_test_tta_main.mat --kaggle_csv_log $2/22_test_tta_main.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_freq_track.csv --model_path $2 --model_type SWIN --load $2/22.pth --valid_mat $2/22_test_tta_freq.mat --kaggle_csv_log $2/22_test_tta_freq.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_comm_track.csv --model_path $2 --model_type SWIN --load $2/22.pth --valid_mat $2/22_test_tta_comm.mat --kaggle_csv_log $2/22_test_tta_comm.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_rare_track.csv --model_path $2 --model_type SWIN --load $2/22.pth --valid_mat $2/22_test_tta_rare.mat --kaggle_csv_log $2/22_test_tta_rare.log

#Swin BBN
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_main_track.csv --model_path $2 --model_type SWIN_BBN --load $2/38.pth --valid_mat $2/38_test_tta_main.mat --kaggle_csv_log $2/38_test_tta_main.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_freq_track.csv --model_path $2 --model_type SWIN_BBN --load $2/38.pth --valid_mat $2/38_test_tta_freq.mat --kaggle_csv_log $2/38_test_tta_freq.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_comm_track.csv --model_path $2 --model_type SWIN_BBN --load $2/38.pth --valid_mat $2/38_test_tta_comm.mat --kaggle_csv_log $2/38_test_tta_comm.log
python3 test_template_TTA.py --img_size 384 --batch_size 8 --mode TEST --test_data_dir $1/test --test_data_csv $1/testcase/sample_submission_rare_track.csv --model_path $2 --model_type SWIN_BBN --load $2/38.pth --valid_mat $2/38_test_tta_rare.mat --kaggle_csv_log $2/38_test_tta_rare.log